#!/bin/bash
#Look Library is an app to save and restore the look of MX-Linux Fluxbox
#V.0.0.3 by Melber 14 June 2022
#License: GPL-3.0+
#mxcr-icon based on yad icon from papirus icon set
#Changelog
#added multiple tint2 panels

#define some variables

TITLE="MXFB-Look-Library"
CLASS="mxfblook"
MXLKPATH="$HOME/.config/mxfb-look"
ICONPATH="/usr/share/pixmaps/mxcr-icon.png"
#HELPPATH="/usr/share/pixmaps/mxrr-help.png"


#delete stylelist and tempclr after use
#trap "rm -r "$MXLKPATH/tempdir" " EXIT

#create path
if [ ! -d $MXLKPATH ]; then

mkdir $MXLKPATH

fi

#create looks folder

if [ ! -d $MXLKPATH/looks ]; then

  mkdir -p $MXLKPATH/looks

fi


#create tempdir

if [ ! -d $MXLKPATH/tempdir ]; then

  mkdir -p $MXLKPATH/tempdir

fi

#make Default look file

if [ ! -f $MXLKPATH/looks/MXFB-default.look ]; then

printf "gtk-theme-name=mx-comfort\ngtk-icon-theme-name=Papirus-mxblue-darkpanes\ngtk-theme-name=\"mx-comfort\"\ngtk-icon-theme-name=\"Papirus-mxblue-darkpanes\"\nsession.styleFile: ~/.fluxbox/styles/MX-comfort\n1\n$HOME/.config/tint2/tint2rc\nx\n@import \"/usr/share/rofi/themes/glue_pro_blue.rasi\"\nfile=/usr/share/backgrounds/Honesty.jpg" > $MXLKPATH/looks/MXFB-default.look

fi

#make Test look file

if [ ! -f $MXLKPATH/looks/test.look ]; then

printf "gtk-theme-name=Numix\ngtk-icon-theme-name=Numix\ngtk-theme-name=\"Numix\"\ngtk-icon-theme-name=\"Numix\"\nsession.styleFile: /usr/share/fluxbox/styles/debian-blue\n1\n$HOME/.config/tint2/grayblue-tint2rc\nx\n@import \"/usr/share/rofi/themes/Indego.rasi\"\nfile=/usr/share/backgrounds/MX_KXF_Blues.jpg" > $MXLKPATH/looks/test.look

fi

#make Test2 look file

if [ ! -f $MXLKPATH/looks/test2.look ]; then

printf "gtk-theme-name=Matcha-dark-sea\ngtk-icon-theme-name=HighContrast\ngtk-theme-name=\"Matcha-dark-sea\"\ngtk-icon-theme-name=\"HighContrast\"\nsession.styleFile: /usr/share/fluxbox/styles/Shade\n2\n$HOME/.config/tint2/graytop-tint2rc\n$HOME/.config/tint2/traditional-tint2rc\n@import \"/usr/share/rofi/themes/fancy.rasi\"\nfile=/usr/share/backgrounds/Big_Bee.jpg" > $MXLKPATH/looks/test2.look

fi


#################################
# function save look

save_look() {
#define some variables

TITLE="MXFB-Look-Library"
CLASS="mxfblook"
MXLKPATH="$HOME/.config/mxfb-look"
ICONPATH="/usr/share/pixmaps/mxcr-icon.png"

#read current look components

#theme and icons
LKTHEME="$(grep "gtk-theme-name" $HOME/.config/gtk-3.0/settings.ini)"
LKICON="$(grep "gtk-icon-theme-name" $HOME/.config/gtk-3.0/settings.ini)"
LKTHEME2="$(grep "gtk-theme-name" $HOME/.gtkrc-2.0)"
LKICON2="$(grep "gtk-icon-theme-name" $HOME/.gtkrc-2.0)"


#fluxbox style
LKFLUXSTYLE="$(grep "styles" $HOME/.fluxbox/init)"

#tint2
TINTNUM="$(wc -l < $HOME/.config/tint2/tint2-sessionfile)"
LKTINT1="$(grep "tint2" $HOME/.config/tint2/tint2-sessionfile | sed -n 1p)"
LKTINT2="$(grep "tint2" $HOME/.config/tint2/tint2-sessionfile | sed -n 2p)"

if [ $TINTNUM = 1 ]; then
LKTINT2="x"
fi

#rofi
LKROFI="$(grep "themes" $HOME/.config/rofi/config.rasi)"

#background
LKBACK="$(grep "file=" $HOME/.config/nitrogen/bg-saved.cfg | sed -n 2p)"

if [ "$LKBACK" = "" ]; then
LKBACK="$(grep "file=" $HOME/.config/nitrogen/bg-saved.cfg)"
fi


#make temp file
echo ""$LKTHEME" "$LKICON" "$LKTHEME2" "$LKICON2" "$LKFLUXSTYLE" "$TINTNUM" "$LKTINT1" "$LKTINT2" "$LKROFI" "$LKBACK"" > $MXLKPATH/tempdir/looktmp.txt


#amend temp
cd $MXLKPATH/tempdir

sed -i "s/gtk-theme-name\=/ /g" looktmp.txt
sed -i "s/gtk-icon-theme-name\=/ /g" looktmp.txt
sed -i "s/session\.styleFile\:/ /g" looktmp.txt
sed -i "s/\$HOME\/\.config\/tint2\// /g" looktmp.txt
sed -i "s/\@import/ /g" looktmp.txt
sed -i "s/file\=/ /g" looktmp.txt
sed -i "s/\"/ /g" looktmp.txt


#read temp

read -r -a YADFILL < looktmp.txt

LKTH="${YADFILL[0]}"
LKIC="${YADFILL[1]}"
LKFS="${YADFILL[4]}"
LKTI1="${YADFILL[6]}"
LKTI2="${YADFILL[7]}"
LKRO="${YADFILL[8]}"
LKBG="${YADFILL[9]}"


#MAIN

MAIN=(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --borders=20 --center --width=600 --height=400 --fixed --form --columns=1 --align=left --separator="" --button="gtk-quit":1 --button="Save Look":0 \
--text="\n<b>Current Settings.\n</b>\n
GTK Theme: <b>"$LKTH"</b>\n
Gtk Icons: <b>"$LKIC"</b>\n
Fluxbox Style: <b>"$LKFS"</b>\n
Tint2 Panel: <b>"$LKTI1" "$LKTI2"</b>\n
Rofi: <b>"$LKRO"</b>\n
Wallpaper: <b>"$LKBG"</b>\n"
--field="Save Look as" "New-Look-Name"\
)
NEWNAME=$("${MAIN[@]}")
(($?==0)) && echo "$NEWNAME" > $MXLKPATH/tempdir/tempname.txt

GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

elif [ "$GETOUT" = 0 ]; then

read NEWNAME < $MXLKPATH/tempdir/tempname.txt

fi


#check new Look name is not empty and forbid MXFB-default overwrite

while [ -z "$NEWNAME" -o "$NEWNAME" = 'MXFB-default' ]; do

  NEWNAME=$(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --text="Look name "$NEWNAME" is protected. Choose another name." --form --center --borders=20 --separator="" \
  --field="<b>Name for new style</b>":LBL " " \
  --field=" " "$NEWNAME-new" )

    GETOUT=$(echo "$?")

    if [ "$GETOUT" != 0 ]; then

    exit

    fi

done


#check if new Look name exists, if yes ask if overwrite or different name

cd $MXLKPATH/looks

while [ -f $NEWNAME.look ]; do

yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --fixed --text="A Look with this name already exists. \n\nDo you want to overwrite <b>"$NEWNAME"</b>\nor save as a different name\n" --button="Overwrite $NEWNAME":2 --button="Save as different name":3 --text-align=center --center --borders=20\

case $? in

2) rm -r $MXLKPATH/looks/$NEWNAME.look ;;

3) NEWNAME=$(yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --form --center --borders=20 --separator="" \
--field="<b>Name for New Look</b>":LBL " " \
--field=" " "$NEWNAME-new" )    ;;

252) exit 0    ;;

esac
done

##################################

echo ""$LKTHEME"
"$LKICON"
"$LKTHEME2"
"$LKICON2"
session.styleFile: "$LKFS"
"$TINTNUM"
"$LKTINT1"
"$LKTINT2"
@import \""$LKRO"\"
"$LKBACK"" > $MXLKPATH/looks/"$NEWNAME".look

  yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=250 --fixed --center --borders=20 --text="All done!\n\nLook has been saved as <b>$NEWNAME</b>" --text-align=center --button="OK" \

exit
}



############################################################
#function restore look

restore_look() {
#define some variables

TITLE="MXFB-Look-Library"
CLASS="mxfblook"
MXLKPATH="$HOME/.config/mxfb-look"
ICONPATH="/usr/share/pixmaps/mxcr-icon.png"


#read saved looks
cd $MXLKPATH/looks
ls -f *.look > $MXLKPATH/tempdir/looklist.txt


#select look to restore

LOOKRESTORE=$( yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --text="\n<b> Choose which look to restore</b>\n" --center --width=400 --height=300 --center --list --no-headers --column=Style --separator="" < $MXLKPATH/tempdir/looklist.txt )

GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

fi

#read Settings for new look

cd $MXLKPATH/looks

mapfile LKRE < $LOOKRESTORE

LKTHEMENEW="${LKRE[0]}"
LKICONNEW="${LKRE[1]}"
LKTHEMENEW2="${LKRE[2]}"
LKICONNEW2="${LKRE[3]}"
LKFSNEW="${LKRE[4]}"
TINTNUMNEW="${LKRE[5]}"
LKTINT1NEW="${LKRE[6]}"
LKTINT2NEW="${LKRE[7]}"
LKROFINEW="${LKRE[8]}"
LKBACKNEW="${LKRE[9]}"

LKTHEMENEW=$(echo "${LKTHEMENEW}" | sed -e 's/[]$.*[\^]/\\&/g' )
LKICONNEW=$(echo "${LKICONNEW}" | sed -e 's/[]$.*[\^]/\\&/g' )
LKTHEMENEW2=$(echo "${LKTHEMENEW2}" | sed -e 's/[]$.*[\^]/\\&/g' )
LKICONNEW2=$(echo "${LKICONNEW2}" | sed -e 's/[]$.*[\^]/\\&/g' )
LKFSNEW=$(echo "${LKFSNEW}" | sed -e 's/[]$\/*[\^]/\\&/g' )
#LKTINTNEW=$(echo "${LKTINTNEW}" | sed -e 's/[]$\/*[\^]/\\&/g' )
LKROFINEW=$(echo "${LKROFINEW}" | sed -e 's/[]$\/*[\^]/\\&/g' )
LKBACKNEW=$(echo "${LKBACKNEW}" | sed -e 's/[]$\/*[\^]/\\&/g' )

#read current look components

#theme and icons
LKTHEMEOLD="$(grep "gtk-theme-name" $HOME/.config/gtk-3.0/settings.ini)"
LKICONOLD="$(grep "gtk-icon-theme-name" $HOME/.config/gtk-3.0/settings.ini)"
LKTHEMEOLD2="$(grep "gtk-theme-name" $HOME/.gtkrc-2.0)"
LKICONOLD2="$(grep "gtk-icon-theme-name" $HOME/.gtkrc-2.0)"

#fluxbox style
LKFSOLD="$(grep "styles" $HOME/.fluxbox/init)"

#tint2
LKTINT1OLD="$(grep "tint2" $HOME/.config/tint2/tint2-sessionfile | sed -n 1p)"
LKTINT2OLD="$(grep "tint2" $HOME/.config/tint2/tint2-sessionfile | sed -n 2p)"

#rofi
LKROFIOLD="$(grep "themes" $HOME/.config/rofi/config.rasi)"

#background
LKBACKOLD="$(grep "file=" $HOME/.config/nitrogen/bg-saved.cfg)"

LKTHEMEOLD=$(echo "${LKTHEMEOLD}" | sed -e 's/[]$.*[\^]/\\&/g' )
LKICONOLD=$(echo "${LKICONOLD}" | sed -e 's/[]$.*[\^]/\\&/g' )
LKTHEMEOLD2=$(echo "${LKTHEMEOLD2}" | sed -e 's/[]$.*[\^]/\\&/g' )
LKICONOLD2=$(echo "${LKICONOLD2}" | sed -e 's/[]$.*[\^]/\\&/g' )
LKFSOLD=$(echo "${LKFSOLD}" | sed -e 's/[]$\/*[\^]/\\&/g' )
#LKTINTOLD=$(echo "${LKTINTOLD}" | sed -e 's/[]$\/*[\^]/\\&/g' )
LKROFIOLD=$(echo "${LKROFIOLD}" | sed -e 's/[]$\/*[\^]/\\&/g' )
LKBACKOLD=$(echo "${LKBACKOLD}" | sed -e 's/[]$\/*[\^]/\\&/g' )


#make temp file
echo ""$LKTHEMENEW" "$LKICONNEW" "$LKTHEMENEW2" "$LKICONNEW2" "$LKFSNEW" "$INTNUMNEW" "$LKTINT1NEW" "$LKTINT2NEW" "$LKROFINEW" "$LKBACKNEW"" > $MXLKPATH/tempdir/looktmp-new.txt

#amend temp
cd $MXLKPATH/tempdir

sed -i "s/gtk-theme-name\=/ /g" looktmp-new.txt
sed -i "s/gtk-icon-theme-name\=/ /g" looktmp-new.txt
sed -i "s/session\.styleFile\:/ /g" looktmp-new.txt
sed -i "s/\$HOME\/\.config\/tint2\// /g" looktmp-new.txt
sed -i "s/\@import/ /g" looktmp-new.txt
sed -i "s/file\=/ /g" looktmp-new.txt
sed -i "s/\"/ /g" looktmp-new.txt


#read temp

read -r -a NEWFILL < looktmp-new.txt

NLKTH="${NEWFILL[0]}"
NLKIC="${NEWFILL[1]}"
NLKFS="${NEWFILL[4]}"
NTINU="${NEWFILL[5]}"
NLKTI1="${NEWFILL[6]}"
NLKTI2="${NEWFILL[7]}"
NLKRO="${NEWFILL[8]}"
NLKBG="${NEWFILL[9]}"

if [ $NLKTI2 = x ]; then
NLKTI2=""
fi

#RESTOREMAIN

yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --borders=20 --center --width=600 --height=400 --fixed --button="gtk-quit":1 --button="Restore Look":0 \
--text="\n<b>These settings will be restored.\n</b>\n
GTK Theme: <b>"$NLKTH"</b>\n
Gtk Icons: <b>"$NLKIC"</b>\n
Fluxbox Style: <b>"$NLKFS"</b>\n
Tint2: <b>"$NLKTI1" "$NLKTI2"</b>\n
Rofi: <b>"$NLKRO"</b>\n
Wallpaper: <b>"$NLKBG"</b>\n"\


GETOUT=$(echo "$?")

if [ "$GETOUT" != 0 ]; then

  exit

elif [ "$GETOUT" = 0 ]; then

#Edit Config files

#gtk
cd ~/.config/gtk-3.0
sed -i -e "s/${LKTHEMEOLD}/${LKTHEMENEW}/g" settings.ini
sed -i -e "s/${LKICONOLD}/${LKICONNEW}/g" settings.ini

cd ~
sed -i -e "s/${LKTHEMEOLD2}/${LKTHEMENEW2}/g" .gtkrc-2.0
sed -i -e "s/${LKICONOLD2}/${LKICONNEW2}/g" .gtkrc-2.0


#gtk bash
function reload_gtk_theme() {
  theme=$(gsettings get org.gnome.desktop.interface gtk-theme)
  gsettings set org.gnome.desktop.interface gtk-theme ''
  sleep 1
  gsettings set org.gnome.desktop.interface gtk-theme $theme
}

reload_gtk_theme


#fluxbox
cd ~/.fluxbox
sed -i -e "s/${LKFSOLD}/${LKFSNEW}/g"  ~/.fluxbox/init
fluxbox-remote restart

#tint
cd ~/.config/tint2

if [ $TINTNUMNEW = 2 ]; then

rm tint2-sessionfile
killall tint2
LKTINTNEWA=$(basename "$LKTINT1NEW")
LKTINTNEWB=$(basename "$LKTINT2NEW")
printf "$HOME/.config/tint2/$LKTINTNEWA\n$HOME/.config/tint2/$LKTINTNEWB" >> ~/.config/tint2/tint2-sessionfile
echo "$LKTINTNEWA"
echo "$LKTINTNEWB"

tint2 -c $HOME/.config/tint2/$LKTINTNEWA >/dev/null 2>&1 &  disown
tint2 -c $HOME/.config/tint2/$LKTINTNEWB >/dev/null 2>&1 &  disown

else

rm tint2-sessionfile
killall tint2
LKTINTNEWA=$(basename "$LKTINT1NEW")
echo "$HOME/.config/tint2/$LKTINTNEWA" >> ~/.config/tint2/tint2-sessionfile
tint2 -c $HOME/.config/tint2/$LKTINTNEWA >/dev/null 2>&1 &  disown

fi


#rofi
cd $HOME/.config/rofi/
sed -i -e "s/${LKROFIOLD}/${LKROFINEW}/g" config.rasi

#background
cd $HOME/.config/nitrogen
sed -i -e "s/${LKBACKOLD}/${LKBACKNEW}/g" bg-saved.cfg
cd $MXLKPATH/tempdir
echo "$LKBACKNEW" > nitrotemp.txt
sed -i "s/file\=//g" nitrotemp.txt
read LKNITRO < nitrotemp.txt
nitrogen --set-zoom-fill --save "$LKNITRO"

fi

}

export -f save_look restore_look

yad --title="$TITLE" --class="$CLASS" --window-icon="$ICONPATH" --width=400 --height=200 --fixed --center --borders=20 --text-align=center --text="<b>You can save the current look or restore a saved look</b>\n\nA look is comprised of the following elements\n- Gtk-Theme\n- Gtk-Icon\n- Fluxbox Style\n- Tint2 Panel\n- Rofi Theme\n- Wallpaper\n\n" --button="gtk-close" --button="Restore Look":"bash -c restore_look" --button="Save Current Look":"bash -c save_look" \
